### ISSUE TITLE
Use the Django Deployment Checklist before turning off Demo mode

### ISSUE THREAD

**Issue by punchagan** [thatte-idli-kaal-soup/sotg-accreditation-tracker#20]
Django's deployment checklist lists a bunch of useful things to check before deploying to production.  It would be worth going through the checklist before advertising the app. 
https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

**Comment by punchagan** [comment]
Demo mode has already been turned off. But, going through the checklist and making recommended changes is important!

**Comment by punchagan** [comment]
- [x] Secret Key set
- [x] Debug mode turned off
- [x] Allowed hosts
- [x] Databases
- [x] Caches
- [x] No emails
- [x] No static files
- [x] No uploads
- [x] No local media
- [x] `python manage.py check --delpoy`
  Except for the HSTS setting, which seems like a risky thing to do if we move the app away from Heroku at some point. Leaving this turned off, for now.
